### ISSUE TITLE
Mac and Win Compilation

### ISSUE THREAD

**Issue by nay-seven** [WrongPeople/WrongPeopleVCV#1]
Hello,
Your plug-ins looks really promising !
I've create the French VCV Facebook group, and ask if someone can compile your plug-ins, hollyday time so no answer, someone ask too on the official group but all have errors , except Linux guy. 
Do you plan to submit them to official plugin manager ? or give us some releases ? ;-)
_( i don't compile myself, so can't help on errors, sorry)_
Best

**Comment by WrongPeople** [comment]
Hi.
Yesterday I [submitted](https://github.com/VCVRack/library/issues/584) my plugin to the library.
Also I fixed compilation on Windows and created the [pre-release](https://github.com/WrongPeople/WrongPeopleVCV/releases/tag/v1.0.0-alpha.0) with Windows and Linux builds, so you can try them.

**Comment by nay-seven** [comment]
ok, thanks for the info, 
Will wait a bit, need the Mac release ;-)

**Comment by WrongPeople** [comment]
Added Mac build.
