### ISSUE TITLE
midi player is not send V/oct signal and crashes

### ISSUE THREAD

**Issue by ghost** [WrongPeople/WrongPeopleVCV#3]

**Comment by WrongPeople** [comment]
Show your MIDI file pls.

**Comment by ghost** [comment]
Maybe its my setup.  Its any midi file I load.  Is there a routing sceme?

**Comment by mocmichal** [comment]
I have experienced crash as well- with this MIDI file - it stops and crashes  at exactly 5:00 sec.
[AUD_DS1287.zip](https://github.com/WrongPeople/WrongPeopleVCV/files/3600686/AUD_DS1287.zip)

**Comment by WrongPeople** [comment]
Can I see the Rack log?

**Comment by mocmichal** [comment]
here you go:
[log.zip](https://github.com/WrongPeople/WrongPeopleVCV/files/3600736/log.zip)

**Comment by WrongPeople** [comment]
Fixed.

**Comment by ghost** [comment]
Will this be submitted back through VCV rack updates?

**Comment by WrongPeople** [comment]
Sure.
I planning new release on this week.

**Comment by ghost** [comment]
Yay,  If only there was a multi-midi clip triggerable version of this to cycle through several possible midi clips with trigger buttons etc.  Also being able to set the speed of the midi file playback  /2 x2 start position and ending position - stuff like that.  

 nice job.
