### ISSUE TITLE
Information about Tourette

### ISSUE THREAD

**Issue by omricohenmusic** [WrongPeople/WrongPeopleVCV#5]
Hi!
I would like to make a video about your collection and include also Tourette but I cannot seem to find any information about it and how it works. Could you please add some more information about it and its functions? 
Thanks,
Omri

**Comment by WrongPeople** [comment]
Hello.
I will add a description of the Tourette module in the coming days.

**Comment by WrongPeople** [comment]
Done.

**Comment by omricohenmusic** [comment]
Thank you so much!
